name: Auto Sync branches

on:
  pull_request:
    types:
      - closed
    branches:
      - staging

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    uses: ./.github/workflows/sync_branch.yaml