name: Auto Merge

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    name: Auto merge if the PR is approved and has label 'auto-merge'

    steps:
    - name: Check PR approved
      if: github.event.review.state == 'approved'
      run: echo "This PR was approved and ready to auto-merge"

    - name: Auto-merge
      id: automerge
      # https://github.com/pascalgn/automerge-action
      uses: "pascalgn/automerge-action@eb68b061739cb9d81564f8e812d0b3c45f0fb09a" # v0.15.5
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "auto-merge"  # The labels that need to be present for a pull request to be merged
        MERGE_METHOD: "merge"
        MERGE_COMMIT_MESSAGE: "Auto merged by git action after approved"
        MERGE_REQUIRED_APPROVALS: "1" # Count of required approvals
