name: Sync branches

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - staging

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches

    permissions:
      pull-requests: write
      contents: write

    strategy:
      matrix:
        branches: ["release/incy", "release/kiwi", "release/tidy", "release/nike", "release/core"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check branch exists
        id: check-branch-exists
        run: |
            if [[ -n $(git ls-remote --heads origin ${{ inputs.branch }}) ]]; then
                echo "exists=true" >> $GITHUB_OUTPUT
            else
                echo "exists=false" >> $GITHUB_OUTPUT          
            fi
        shell: bash

      - name: Opening pull request staging -> ${{ matrix.branches }}
        if: steps.check-branch-exists.outputs.exists == 'true'
        id: create-pr
        # https://github.com/marketplace/actions/sync-branches
        uses: uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "staging"
          TO_BRANCH: ${{ matrix.branches }}
          PULL_REQUEST_TITLE: ":twisted_rightwards_arrows: [Auto] Sync staging to ${{ matrix.branches }}"
          CONTENT_COMPARISON: true
          LABELS: '["sync-pr"]'
          REVIEWERS: '["noraincode"]'
        