name: Sync branches

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - staging

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches

    strategy:
      matrix:
        branches: ["release/incy", "release/kiwi", "release/tidy", "release/nike", "release/core"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check branch exists
        id: check-branch-exists
        # https://github.com/marketplace/actions/branch-exists
        uses: GuillaumeFalourd/branch-exists@v1
        with: 
          branch: ${{ matrix.branches }}
      - if: steps.check-branch-exists.outputs.exists == 'false'
        run: echo '${{ matrix.branches }} Branch NOT FOUND'

      - name: Opening pull request staging -> ${{ matrix.branches }}
        if: steps.check-branch-exists.outputs.exists == 'true'
        id: create-pr
        # https://github.com/marketplace/actions/sync-branches
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "staging"
          TO_BRANCH: ${{ matrix.branches }}
          PULL_REQUEST_TITLE: ":twisted_rightwards_arrows: [Auto] Sync staging to ${{ matrix.branches }}"
          CONTENT_COMPARISON: true
          LABELS: '["sync-pr"]'
          REVIEWERS: '["noraincode"]'

      - name: Auto merge
        if: steps.create-pr.outputs.PULL_REQUEST_NUMBER != ''
        id: automerge
        uses: pascalgn/automerge-action@v0.15.5
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: merge
          PULL_REQUEST: ${{ steps.create-pr.outputs.PULL_REQUEST_NUMBER }}