name: Sync branches

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - staging

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # - name: Check PR exists

      - name: Opening pull request staging -> incy
        id: pull
        # https://github.com/marketplace/actions/sync-branches
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "staging"
          TO_BRANCH: "release/incy"
          PULL_REQUEST_TITLE: ":twisted_rightwards_arrows: [Auto] Sync staging to release/incy"
          CONTENT_COMPARISON: true
          TEAM_REVIEWERS: ["noraincode"]